<?php
require_once 'src/config.php';
require_once 'src/financial_calculations.php';

// Simulate standard dashboard parameters (same as in global context)
$startDateParam = date('Y-m-01', strtotime("-6 months"));
$endDateParam = date('Y-m-t', strtotime("+5 months"));

// Fetch partnerships (admin view simulation)
$stmt = $pdo->query("SELECT p.*, pt.name as owner_name FROM partnerships p JOIN partners pt ON p.owner_id = pt.id");
$partnerships = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Fetch all lots and liquidations
$partnershipLots = [];
$lots_stmt = $pdo->query("SELECT * FROM partnership_lots ORDER BY slaughter_date ASC");
while ($row = $lots_stmt->fetch(PDO::FETCH_ASSOC)) {
    $partnershipLots[$row['partnership_id']][] = $row;
}

$partnershipLiquidations = [];
$liq_stmt = $pdo->query("SELECT * FROM partnership_liquidations ORDER BY date ASC");
while ($row = $liq_stmt->fetch(PDO::FETCH_ASSOC)) {
    $partnershipLiquidations[$row['partnership_id']][] = $row;
}

$total_yield_period = 0;
$total_yield_cumulative = 0;
$global_simulated_futures_total = 0;
$total_initial_p = 0;
$total_actual_liq = 0;

foreach ($partnerships as $p) {
    $initial_p = floatval($p['total_value']);
    // Card logic for initial principal (matches dashboard_stats.php line 135)
    if ($p['start_date'] <= $endDateParam) {
        $total_initial_p += $initial_p;
    }

    $lots = $partnershipLots[$p['id']] ?? [];
    $liqs = $partnershipLiquidations[$p['id']] ?? [];

    // Card logic for actual liquidations (matches dashboard_stats.php line 144/228)
    foreach ($liqs as $l) {
        if ($l['date'] <= $endDateParam) {
            $total_actual_liq += floatval($l['amount_total']);
        }
    }

    // --- LIFE YIELD ---
    $allTimeState = calculatePartnershipState($p, $lots, $liqs, date('Y-m-d'));
    $current_all_time_balance = $allTimeState['current_balance'];
    $furthestLotRate = 0;
    if (!empty($lots)) {
        usort($lots, function($a, $b){ return strtotime($a['slaughter_date']) - strtotime($b['slaughter_date']); });
        $furthestLotRate = floatval($lots[count($lots)-1]['monthly_rate']);
    }
    // Projected value at absolute maturity
    $matureBalance = calculateProjectedBalance($current_all_time_balance, date('Y-m-d'), $furthestLotRate, $lots, $liqs);
    $total_liq_life = 0;
    foreach ($liqs as $l) $total_liq_life += floatval($l['amount_total']);
    
    // Total profit generated by this contract across its whole life
    $true_life_profit = ($matureBalance + $total_liq_life) - $initial_p;
    
    // Total Yield for the dashboard would be Sum(Calibrated Segments Life) = true_life_profit
    $total_yield_cumulative += $true_life_profit;

    // --- SIMULATED FUTURES LOGIC (Chart Logic) ---
    $totalActualLiqForSim = $total_liq_life;
    $simLots = $lots;
    usort($simLots, function($a, $b) { return strtotime($a['slaughter_date']) - strtotime($b['slaughter_date']); });
    foreach ($simLots as $slot) {
        $projValue = floatval($slot['projected_value']);
        if ($totalActualLiqForSim >= $projValue) {
            $totalActualLiqForSim -= $projValue;
        } else {
            $uncovered = $projValue - $totalActualLiqForSim;
            $totalActualLiqForSim = 0;
            // The simulation logic says: if slaughter happens before endDateParam, we subtract it.
            if (max(date('Y-m-d'), $slot['slaughter_date']) <= $endDateParam) {
                $global_simulated_futures_total += $uncovered;
            }
        }
    }
}

// Chart Final Balance = (Initial up to end) - (Actual up to end + Simulated up to end)
$chart_final_balance = $total_initial_p - ($total_actual_liq + $global_simulated_futures_total);

// The Yield we accrued in segments within [Start, End]
// This is what the card currently shows.
$total_yield_period_card = 0;
foreach ($partnerships as $p) {
    // We would need to generate segments here, but we can verify comparison first.
}

echo "TEST RESULTS:\n";
echo "Date Range: $startDateParam to $endDateParam\n";
echo "------------------------------------------\n";
echo "Total Cumulative Profit (All Involved Contracts): " . number_format($total_yield_cumulative, 2, ',', '.') . "\n";
echo "Card 'Rendimento Total' (Window Filter): [SEE DASHBOARD VALUE]\n";
echo "Result Chart (White Line Final Value): " . number_format($chart_final_balance, 2, ',', '.') . "\n";
echo "Profit according to Chart Balance (Absolute): " . number_format(-$chart_final_balance, 2, ',', '.') . "\n";

echo "\nCONCLUSION:\n";
if (abs($total_yield_cumulative - (-$chart_final_balance)) < 1) {
    echo "If you remove the 'startDateParam' check, the Card will show exactly the value captured by the chart line (" . number_format($total_yield_cumulative, 2, ',', '.') . ").\n";
} else {
    echo "There is a gap of " . number_format($total_yield_cumulative + $chart_final_balance, 2, ',', '.') . ". This happens if some investments started AFTER the chart period or if we are looking at total life profit vs only profit up to the window.\n";
}
?>
